SELECT CONTEST_ID, HACKER_ID, NAME, SUM(TOTAL_SUBMISSONS),
            SUM(TOTAL_ACCEPTED_SUBMISSONS), SUM(TOTAL_VIEWS), SUM(TOTAL_UNIQUE_VIEWS)
FROM A
WHERE SUM(TOTAL_SUBMISSONS),
            SUM(TOTAL_ACCEPTED_SUBMISSONS), SUM(TOTAL_VIEWS), SUM(TOTAL_UNIQUE_VIEWS) != 0
ORDER BY CONTEST_ID;