-- STUDENTS, FRIENDS, PACKAGES

--THE CORRECT ANSWER
SELECT S.NAME
FROM STUDENTS S, FRIENDS F, PACKAGES P1, PACKAGES P2
WHERE S.ID = F.ID AND S.ID = P1.ID AND F.FRIEND_ID = P2.ID AND P1.SALARY < P2.SALARY
ORDER BY P2.SALARY;


-- THE WRONG ANSWER
SELECT S.NAME
FROM (
        SELECT F.ID
        FROM FRIENDS F INNER JOIN PACKAGES P ON F.FRIEND_ID =P.ID
        WHERE F.ID = P.ID AND P.SALARY > (
                SELECT P.SALSARY
                FROM FRIENDS F INNER JOIN PACKAGES P ON F.ID = P.ID
                WHERE F.ID = P.ID)
        ) I INNER JOIN STUDENTS S ON I.ID = S.ID
ORDER BY P.SALARY;