-- THE WRONG ANSWER
SELECT S.NAME
FROM (
        SELECT F.ID
        FROM FRIENDS F INNER JOIN PACKAGES P ON F.FRIEND_ID =P.ID
        WHERE F.ID = P.ID AND P.SALARY > (
                SELECT P.SALSARY
                FROM FRIENDS F INNER JOIN PACKAGES P ON F.ID = P.ID
                WHERE F.ID = P.ID)
        ) I INNER JOIN STUDENTS S ON I.ID = S.ID
ORDER BY P.SALARY;