-- Draw The Triangle 1

-- 1~10까지 연속된 숫자 조회
SELECT LEVEL AS NO
FROM DUAL
CONNECT BY LEVEL <= 10;

SELECT RPAD('*', x)
FROM (SELECT LEVEL x FROM DUAL CONNECT BY LEVEL <= 10 ORDER BY LEVEL DESC)
WHERE MOD(x,2)=0;


SELECT LEVEL x FROM DUAL CONNECT BY LEVEL <= 10 ORDER BY LEVEL DESC;

